name: Build and deploy Node.js app to Azure Web App - bookwebapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install, build, and test
        run: |
          npm ci
          npm run build --if-present
          npm run test --if-present
      
      - name: Compress artifact for deployment job
        run: |
          mkdir deploy
          cp -r public deploy/
          cp -r .next deploy/
          cp -r node_modules deploy/
          cp package.json deploy/
          cp next.config.js deploy/
          cd deploy
          powershell Compress-Archive -Path . -DestinationPath ../node-app.zip
        shell: pwsh

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: node-app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: Unzip artifact
        run: |
          mkdir deploy
          unzip node-app.zip -d deploy
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'bookwebapp'
          slot-name: 'Production'
          package: deploy

      - name: Start the Web App
        run: |
          az webapp start --name bookwebapp --resource-group bookreview1_group

      - name: Fetch Deployment Logs
        run: |
          curl -u ${{ secrets.AZURE_USER }}:${{ secrets.AZURE_PASS }} "https://bookwebapp.scm.azurewebsites.net/api/deployments/latest/log"
